version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
#    ports:
#      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  backend:
    build:
      context: .
    command: bash -c "sleep 15
      && python manage.py migrate
      && python manage.py create_django_superuser
      && gunicorn task_board.wsgi -b 0.0.0.0:8080"
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend
  frontend:
    build: ./task_board/frontend
    ports:
      - 8011:80
    depends_on:
      - nginx